### ISSUE TITLE
нет доступа к редислабс

### ISSUE THREAD

**Issue by wesely2048** [igorzakhar/quiz-bot#1]
В связи с последними событиями с российских ip адресов нет доступа к редислабс.

**Comment by igorzakhar** [comment]
На самом деле это не является проблемой. Есть, как минимум, 2 варинта в данном случае:

1. Задеплоить бота на каком-нибудь зарубежном хостинге. Демо чат-боты, из этого репозитория, размещёны на [Heroku](heroku.com). Проверял вчера, оба бота в работе, правда пришлось их перезапускать т.к. использую бесплатный тариф и в конце каждого месяца кончаются [free dyno hours](https://www.heroku.com/dynos) (мне на месяц дается 1000 free dyno hours т.к. привязана карта).
2. Поднять Redis локально,  можно использовать Docker. Быстрый и менее трудозатратный способ т.к. не нужно разбираться с деплоингом на [Heroku](heroku.com).
